# Generated by Django 5.2.3 on 2025-07-13 02:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_trafficincident_incidentvote_incidentcomment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='incidentvote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='incidentvote',
            name='incident',
        ),
        migrations.RemoveField(
            model_name='incidentvote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trafficincident',
            name='user',
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('incident_type', models.CharField(choices=[('accident', 'Accidente'), ('traffic_jam', 'Congestión de Tráfico'), ('road_closure', 'Cierre de Vía'), ('construction', 'Obras en Construcción'), ('police_control', 'Control Policial'), ('other', 'Otro')], max_length=20, verbose_name='Tipo de Incidente')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitud')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='incident_photos/', verbose_name='Foto')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='IncidentComment',
        ),
        migrations.DeleteModel(
            name='IncidentVote',
        ),
        migrations.DeleteModel(
            name='TrafficIncident',
        ),
    ]
