# Generated by Django 4.2.11 on 2025-07-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
