# Generated by Django 5.2.3 on 2025-07-14 19:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_incidentvote_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Descripción breve del incidente (máximo 200 caracteres)', max_length=200, validators=[django.core.validators.MinLengthValidator(5, 'El título debe tener al menos 5 caracteres')], verbose_name='Título del incidente')),
                ('description', models.TextField(help_text='Describe el incidente con el mayor detalle posible', max_length=1000, validators=[django.core.validators.MinLengthValidator(10, 'La descripción debe tener al menos 10 caracteres')], verbose_name='Descripción detallada')),
                ('incident_type', models.CharField(choices=[('accident', '🚗 Accidente'), ('construction', '🚧 Construcción'), ('traffic_jam', '🚦 Embotellamiento'), ('road_closure', '🚫 Cierre de vía'), ('police_control', '👮 Control policial'), ('broken_traffic_light', '🔴 Semáforo dañado'), ('pothole', '🕳️ Bache'), ('flooding', '💧 Inundación'), ('vehicle_breakdown', '🔧 Vehículo averiado'), ('protest', '✊ Manifestación'), ('other', '❓ Otro')], help_text='Selecciona el tipo de incidente que mejor describe la situación', max_length=50, verbose_name='Tipo de incidente')),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Coordenada de latitud del incidente', max_digits=10, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Coordenada de longitud del incidente', max_digits=10, verbose_name='Longitud')),
                ('photo', models.ImageField(blank=True, help_text='Imagen opcional del incidente (máximo 5MB)', null=True, upload_to='traffic_incidents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'], message='Solo se permiten archivos JPG, PNG, GIF y WebP')], verbose_name='Foto del incidente')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora cuando se creó el reporte', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el incidente sigue activo', verbose_name='Activo')),
                ('is_verified', models.BooleanField(default=False, help_text='Indica si el incidente ha sido verificado por moderadores', verbose_name='Verificado')),
                ('severity', models.CharField(choices=[('low', '🟢 Baja'), ('medium', '🟡 Media'), ('high', '🔴 Alta'), ('critical', '🚨 Crítica')], default='medium', help_text='Nivel de severidad del incidente', max_length=20, verbose_name='Severidad')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Cuántas veces se ha visto este incidente', verbose_name='Número de vistas')),
                ('address', models.CharField(blank=True, help_text='Dirección aproximada del incidente (se llena automáticamente)', max_length=500, verbose_name='Dirección')),
                ('district', models.CharField(blank=True, help_text='Distrito donde ocurrió el incidente', max_length=100, verbose_name='Distrito')),
                ('user', models.ForeignKey(help_text='Usuario que reportó el incidente', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario reportante')),
            ],
            options={
                'verbose_name': 'Incidente de Tráfico',
                'verbose_name_plural': 'Incidentes de Tráfico',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('confirm', '✅ Confirmar'), ('deny', '❌ Desmentir'), ('resolved', '✔️ Resuelto')], max_length=20, verbose_name='Tipo de voto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de voto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='web.trafficincident', verbose_name='Incidente')),
            ],
            options={
                'verbose_name': 'Voto de Incidente',
                'verbose_name_plural': 'Votos de Incidentes',
            },
        ),
        migrations.CreateModel(
            name='IncidentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500, validators=[django.core.validators.MinLengthValidator(5, 'El comentario debe tener al menos 5 caracteres')], verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='web.trafficincident', verbose_name='Incidente')),
            ],
            options={
                'verbose_name': 'Comentario de Incidente',
                'verbose_name_plural': 'Comentarios de Incidentes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Incident',
        ),
        migrations.AddIndex(
            model_name='trafficincident',
            index=models.Index(fields=['created_at'], name='web_traffic_created_5fef3f_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficincident',
            index=models.Index(fields=['incident_type'], name='web_traffic_inciden_cbb635_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficincident',
            index=models.Index(fields=['user'], name='web_traffic_user_id_0b36ef_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficincident',
            index=models.Index(fields=['latitude', 'longitude'], name='web_traffic_latitud_4475cb_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficincident',
            index=models.Index(fields=['is_active'], name='web_traffic_is_acti_c10d50_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='incidentvote',
            unique_together={('incident', 'user')},
        ),
    ]
