# Generated by Django 4.2.11 on 2025-07-20 02:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alerta_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
