# Generated by Django 5.2.3 on 2025-07-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_trafficincident_incidentvote_incidentcomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficincident',
            name='latitude',
            field=models.DecimalField(decimal_places=7, help_text='Coordenada de latitud del incidente', max_digits=15, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='trafficincident',
            name='longitude',
            field=models.DecimalField(decimal_places=7, help_text='Coordenada de longitud del incidente', max_digits=15, verbose_name='Longitud'),
        ),
    ]
