# Generated by Django 5.2.3 on 2025-07-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_trafficincident_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficincident',
            name='latitude',
            field=models.DecimalField(decimal_places=10, help_text='Coordenada de latitud del incidente', max_digits=18, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='trafficincident',
            name='longitude',
            field=models.DecimalField(decimal_places=10, help_text='Coordenada de longitud del incidente', max_digits=19, verbose_name='Longitud'),
        ),
    ]
