# Generated by Django 4.2.11 on 2025-07-27 21:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificaciones_activas', models.BooleanField(default=True, help_text='Recibir notificaciones de zonas congestionadas', verbose_name='Notificaciones activas')),
                ('radio_notificacion', models.FloatField(default=2.0, help_text='Distancia máxima para recibir notificaciones de congestión', validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(10.0)], verbose_name='Radio de notificación (km)')),
                ('latitud_actual', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True, verbose_name='Latitud actual')),
                ('longitud_actual', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True, verbose_name='Longitud actual')),
                ('ultima_actualizacion_ubicacion', models.DateTimeField(blank=True, null=True, verbose_name='Última actualización de ubicación')),
                ('frecuencia_actualizacion', models.IntegerField(default=30, help_text='Cada cuántos segundos actualizar la ubicación', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(300)], verbose_name='Frecuencia de actualización (segundos)')),
                ('tipos_incidentes_notificar', models.JSONField(blank=True, default=list, help_text='Lista de tipos de incidentes que quiere recibir', verbose_name='Tipos de incidentes a notificar')),
                ('total_notificaciones_recibidas', models.PositiveIntegerField(default=0, verbose_name='Total de notificaciones recibidas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación del perfil')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de última actualización')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'indexes': [models.Index(fields=['latitud_actual', 'longitud_actual'], name='perfil_ubicacion_idx'), models.Index(fields=['notificaciones_activas'], name='perfil_notif_idx'), models.Index(fields=['ultima_actualizacion_ubicacion'], name='perfil_ult_ubic_idx')],
            },
        ),
    ]
