# Generated by Django 4.2.11 on 2025-07-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='enviar_a_todos',
            field=models.BooleanField(default=False),
        ),
    ]
