# Generated by Django 5.2.3 on 2025-07-29 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0002_alerta_enviar_a_todos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio_real', models.DateTimeField(auto_now_add=True)),
                ('estado_entrega', models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Fallido'), ('pendiente', 'Pendiente')], default='enviado', max_length=20)),
                ('zona', models.CharField(blank=True, max_length=255)),
                ('tipo_notificacion', models.CharField(choices=[('sistema', 'Sistema'), ('email', 'Email'), ('push', 'Push'), ('sms', 'SMS')], default='sistema', max_length=50)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='admin_custom.alerta')),
                ('usuario_destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Notificación',
                'verbose_name_plural': 'Historiales de Notificaciones',
                'ordering': ['-fecha_envio_real'],
            },
        ),
    ]
