# Generated by Django 5.2.3 on 2025-07-29 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0003_historialnotificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='destinatarios',
            field=models.ManyToManyField(blank=True, related_name='admin_alertas_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='enviado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_alertas_enviadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
