# Generated by Django 5.2.3 on 2025-07-21 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('ubicacion', models.CharField(blank=True, default='', max_length=200)),
                ('destinatarios', models.ManyToManyField(related_name='alertas_recibidas', to=settings.AUTH_USER_MODEL)),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteColaborativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ubicacion', models.CharField(max_length=100)),
                ('tipo_incidente', models.CharField(max_length=50)),
                ('imagen_geolocalizada', models.ImageField(blank=True, null=True, upload_to='reportes/')),
                ('estado_reporte', models.CharField(choices=[('pendiente', 'Pendiente'), ('probado', 'Probado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('nivel_peligro', models.IntegerField(default=1)),
                ('votos_positivos', models.IntegerField(default=0)),
                ('votos_negativos', models.IntegerField(default=0)),
                ('es_validado', models.BooleanField(default=False)),
                ('usuario_reportador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuarios_votantes', models.ManyToManyField(blank=True, related_name='votos_emitidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
