# Generated by Django 5.2.3 on 2025-07-28 22:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('ubicacion', models.CharField(blank=True, default='', max_length=200)),
                ('destinatarios', models.ManyToManyField(related_name='alertas_recibidas', to=settings.AUTH_USER_MODEL)),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportes_por_pagina', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)])),
                ('mostrar_estadisticas', models.BooleanField(default=True)),
                ('notificaciones_activas', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'configuracion_usuario',
            },
        ),
        migrations.CreateModel(
            name='ReporteColaborativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Descripción breve del incidente (máximo 200 caracteres)', max_length=200, validators=[django.core.validators.MinLengthValidator(5, 'El título debe tener al menos 5 caracteres')], verbose_name='Título del incidente')),
                ('descripcion', models.TextField(help_text='Describe el incidente con el mayor detalle posible', max_length=1000, validators=[django.core.validators.MinLengthValidator(10, 'La descripción debe tener al menos 10 caracteres')], verbose_name='Descripción detallada')),
                ('tipo_incidente', models.CharField(choices=[('accidente', '🚗 Accidente'), ('construccion', '🚧 Construcción'), ('embotellamiento', '🚦 Embotellamiento'), ('cierre_via', '🚫 Cierre de vía'), ('control_policial', '👮 Control policial'), ('semaforo_danado', '🔴 Semáforo dañado'), ('bache', '🕳️ Bache'), ('inundacion', '💧 Inundación'), ('vehiculo_averiado', '🔧 Vehículo averiado'), ('manifestacion', '✊ Manifestación'), ('otro', '❓ Otro')], help_text='Selecciona el tipo de incidente que mejor describe la situación', max_length=50, verbose_name='Tipo de incidente')),
                ('latitud', models.DecimalField(decimal_places=10, default=Decimal('0.0'), help_text='Coordenada de latitud del incidente', max_digits=18, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=10, default=Decimal('0.0'), help_text='Coordenada de longitud del incidente', max_digits=18, verbose_name='Longitud')),
                ('foto', models.ImageField(blank=True, help_text='Imagen opcional del incidente (máximo 5MB)', null=True, upload_to='reportes/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'], message='Solo se permiten archivos JPG, PNG, GIF y WebP')], verbose_name='Foto del incidente')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora cuando se creó el reporte', verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización')),
                ('estado_reporte', models.CharField(choices=[('pendiente', 'Pendiente'), ('probado', 'Probado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('nivel_peligro', models.IntegerField(choices=[(1, '🟢 Bajo'), (2, '🟡 Medio'), (3, '🔴 Alto'), (4, '🚨 Crítico')], default=1)),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Cuántas veces se ha visto este incidente', verbose_name='Número de vistas')),
                ('nombre_via', models.CharField(blank=True, help_text='Nombre de la vía donde ocurrió el incidente', max_length=500, verbose_name='Nombre de la vía')),
                ('distrito', models.CharField(blank=True, help_text='Distrito donde ocurrió el incidente', max_length=100, verbose_name='Distrito')),
                ('is_active', models.BooleanField(default=True, help_text='Marca si el reporte sigue siendo válido o visible', verbose_name='¿Está activo?')),
                ('votos_positivos', models.IntegerField(default=0)),
                ('votos_negativos', models.IntegerField(default=0)),
                ('usuario_reportador', models.ForeignKey(help_text='Usuario que reportó el incidente', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario reportante')),
                ('usuarios_votantes', models.ManyToManyField(blank=True, related_name='votos_emitidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidente de Tráfico',
                'verbose_name_plural': 'Incidentes de Tráfico',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='InteraccionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vista', models.DateTimeField(auto_now=True)),
                ('tiempo_lectura_segundos', models.PositiveIntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporte.reportecolaborativo')),
            ],
            options={
                'db_table': 'interaccion_usuario',
            },
        ),
        migrations.AddIndex(
            model_name='reportecolaborativo',
            index=models.Index(fields=['fecha_creacion'], name='reporte_rep_fecha_c_8aebce_idx'),
        ),
        migrations.AddIndex(
            model_name='reportecolaborativo',
            index=models.Index(fields=['tipo_incidente'], name='reporte_rep_tipo_in_9cd30d_idx'),
        ),
        migrations.AddIndex(
            model_name='reportecolaborativo',
            index=models.Index(fields=['usuario_reportador'], name='reporte_rep_usuario_f806e3_idx'),
        ),
        migrations.AddIndex(
            model_name='reportecolaborativo',
            index=models.Index(fields=['latitud', 'longitud'], name='reporte_rep_latitud_401e71_idx'),
        ),
        migrations.AddIndex(
            model_name='reportecolaborativo',
            index=models.Index(fields=['is_active'], name='reporte_rep_is_acti_62a54a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interaccionusuario',
            unique_together={('usuario', 'reporte')},
        ),
    ]
