# Generated by Django 5.2.3 on 2025-07-26 17:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportecolaborativo',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Incidente de Tráfico', 'verbose_name_plural': 'Incidentes de Tráfico'},
        ),
        migrations.RemoveField(
            model_name='reportecolaborativo',
            name='es_validado',
        ),
        migrations.RemoveField(
            model_name='reportecolaborativo',
            name='imagen_geolocalizada',
        ),
        migrations.RemoveField(
            model_name='reportecolaborativo',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='reportecolaborativo',
            name='usuarios_votantes',
        ),
        migrations.RemoveField(
            model_name='reportecolaborativo',
            name='votos_negativos',
        ),
        migrations.RemoveField(
            model_name='reportecolaborativo',
            name='votos_positivos',
        ),
        migrations.AddField(
            model_name='reportecolaborativo',
            name='distrito',
            field=models.CharField(blank=True, help_text='Distrito donde ocurrió el incidente', max_length=100, verbose_name='Distrito'),
        ),
        migrations.AddField(
            model_name='reportecolaborativo',
            name='foto',
            field=models.ImageField(blank=True, help_text='Imagen opcional del incidente (máximo 5MB)', null=True, upload_to='reportes/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'], message='Solo se permiten archivos JPG, PNG, GIF y WebP')], verbose_name='Foto del incidente'),
        ),
        migrations.AddField(
            model_name='reportecolaborativo',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Marca si el reporte sigue siendo válido o visible', verbose_name='¿Está activo?'),
        ),
        migrations.AddField(
            model_name='reportecolaborativo',
            name='latitud',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.0'), help_text='Coordenada de latitud del incidente', max_digits=18, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='reportecolaborativo',
            name='longitud',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.0'), help_text='Coordenada de longitud del incidente', max_digits=18, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='reportecolaborativo',
            name='nombre_via',
            field=models.CharField(blank=True, help_text='Nombre de la vía donde ocurrió el incidente', max_length=500, verbose_name='Nombre de la vía'),
        ),
        migrations.AddField(
            model_name='reportecolaborativo',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text='Cuántas veces se ha visto este incidente', verbose_name='Número de vistas'),
        ),
        migrations.AlterField(
            model_name='reportecolaborativo',
            name='descripcion',
            field=models.TextField(help_text='Describe el incidente con el mayor detalle posible', max_length=1000, validators=[django.core.validators.MinLengthValidator(10, 'La descripción debe tener al menos 10 caracteres')], verbose_name='Descripción detallada'),
        ),
        migrations.AlterField(
            model_name='reportecolaborativo',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='reportecolaborativo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora cuando se creó el reporte', verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='reportecolaborativo',
            name='nivel_peligro',
            field=models.IntegerField(choices=[(1, '🟢 Bajo'), (2, '🟡 Medio'), (3, '🔴 Alto'), (4, '🚨 Crítico')], default=1),
        ),
        migrations.AlterField(
            model_name='reportecolaborativo',
            name='tipo_incidente',
            field=models.CharField(choices=[('accidente', '🚗 Accidente'), ('construccion', '🚧 Construcción'), ('embotellamiento', '🚦 Embotellamiento'), ('cierre_via', '🚫 Cierre de vía'), ('control_policial', '👮 Control policial'), ('semaforo_danado', '🔴 Semáforo dañado'), ('bache', '🕳️ Bache'), ('inundacion', '💧 Inundación'), ('vehiculo_averiado', '🔧 Vehículo averiado'), ('manifestacion', '✊ Manifestación'), ('otro', '❓ Otro')], help_text='Selecciona el tipo de incidente que mejor describe la situación', max_length=50, verbose_name='Tipo de incidente'),
        ),
        migrations.AlterField(
            model_name='reportecolaborativo',
            name='titulo',
            field=models.CharField(help_text='Descripción breve del incidente (máximo 200 caracteres)', max_length=200, validators=[django.core.validators.MinLengthValidator(5, 'El título debe tener al menos 5 caracteres')], verbose_name='Título del incidente'),
        ),
        migrations.AlterField(
            model_name='reportecolaborativo',
            name='usuario_reportador',
            field=models.ForeignKey(help_text='Usuario que reportó el incidente', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario reportante'),
        ),
        migrations.AddIndex(
            model_name='reportecolaborativo',
            index=models.Index(fields=['fecha_creacion'], name='reporte_rep_fecha_c_8aebce_idx'),
        ),
        migrations.AddIndex(
            model_name='reportecolaborativo',
            index=models.Index(fields=['tipo_incidente'], name='reporte_rep_tipo_in_9cd30d_idx'),
        ),
        migrations.AddIndex(
            model_name='reportecolaborativo',
            index=models.Index(fields=['usuario_reportador'], name='reporte_rep_usuario_f806e3_idx'),
        ),
        migrations.AddIndex(
            model_name='reportecolaborativo',
            index=models.Index(fields=['latitud', 'longitud'], name='reporte_rep_latitud_401e71_idx'),
        ),
        migrations.AddIndex(
            model_name='reportecolaborativo',
            index=models.Index(fields=['is_active'], name='reporte_rep_is_acti_62a54a_idx'),
        ),
    ]
