# Generated by Django 5.2.3 on 2025-07-21 06:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=11)),
                ('tipo_incidente', models.CharField(choices=[('accidente', 'Accidente'), ('congestion', 'Congestión'), ('obra', 'Obra en construcción'), ('manifestacion', 'Manifestación'), ('vehiculo_varado', 'Vehículo varado'), ('otro', 'Otro')], max_length=20)),
                ('estado_reporte', models.CharField(choices=[('pendiente', 'Pendiente'), ('validado', 'Validado'), ('rechazado', 'Rechazado'), ('archivado', 'Archivado')], default='pendiente', max_length=20)),
                ('nivel_peligro', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('imagen_geolocalizada', models.ImageField(blank=True, null=True, upload_to='reportes/')),
                ('votos_positivos', models.IntegerField(default=0)),
                ('votos_negativos', models.IntegerField(default=0)),
                ('es_validado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario_reportador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reporte_trafico',
                'indexes': [models.Index(fields=['usuario_reportador'], name='reporte_tra_usuario_66e242_idx'), models.Index(fields=['estado_reporte'], name='reporte_tra_estado__fe6ebf_idx'), models.Index(fields=['fecha_creacion'], name='reporte_tra_fecha_c_8464c8_idx'), models.Index(fields=['tipo_incidente'], name='reporte_tra_tipo_in_438a37_idx')],
            },
        ),
    ]
