# Generated by Django 5.2.3 on 2025-07-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportecolaborativo',
            name='estado_reporte',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
