# Generated by Django 5.2.3 on 2025-07-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportecolaborativo',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportecolaborativo',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
