# Generated by Django 5.2.3 on 2025-07-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0002_reportecolaborativo_latitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportecolaborativo',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
