# Generated by Django 5.2.3 on 2025-07-26 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0002_alter_reportecolaborativo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportecolaborativo',
            name='usuarios_votantes',
            field=models.ManyToManyField(blank=True, related_name='votos_emitidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportecolaborativo',
            name='votos_negativos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportecolaborativo',
            name='votos_positivos',
            field=models.IntegerField(default=0),
        ),
    ]
