# Generated by Django 5.2.3 on 2025-07-28 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0002_reporte'),
        ('reporte', '0003_alter_reportecolaborativo_ubicacion'),
        ('reporte', '0003_reportecolaborativo_usuarios_votantes_and_more'),
    ]

    operations = [
    ]
